### ISSUE TITLE
Include project stats from github

### ISSUE THREAD

**Issue by rattrayalex** [azat-co/nodeframework#19]
It would be very helpful to see how many stars each project has on github. 

Other helpful stats could include: 
- posts on stackoverflow
- downloads on npm
- issue throughput on github
- number of contributors
- other stats from "the pulse"

**Comment by azat-co** [comment]
@rattrayalex totally, any ideas how to do it on the static GH pages hosting? I wanted to do front-end JS, but cross-domain will prohibit. Another option is to scrape data one in a while and just populate the js/json file stored on this domain.

feel free to make a PR

**Comment by rattrayalex** [comment]
This could work, at least for the most basic item: https://github.com/mdo/github-buttons

**Comment by azat-co** [comment]
@rattrayalex nice! :+1: :smile:

**Comment by rands0n** [comment]
And how would? Only the number of stars next to the name of the framework?

I can help with anything :)

**Comment by azat-co** [comment]
@randsonjs how about something like this? 
![screenshot 2014-09-14 19 18 17](https://cloud.githubusercontent.com/assets/1137314/4266471/a4d1e63e-3c7e-11e4-9375-8caea4253ed6.png) and when you press on "i" it open links 
![screenshot 2014-09-14 19 19 07](https://cloud.githubusercontent.com/assets/1137314/4266478/bba4bff8-3c7e-11e4-942b-27d7ffc40c82.png)

do you think you can add for other frameworks?

**Comment by rands0n** [comment]
@azat-co I am adding one by one by pull request :)

**Comment by azat-co** [comment]
@randsonjs great! I merged and made a few comments! a8b0d5d6e24bd3be140a32a59739862a60e68587 https://github.com/azat-co/nodeframework/pull/21
