### ISSUE TITLE
CompoundJS organization on Github

### ISSUE THREAD

**Issue by rands0n** [azat-co/nodeframework#24]
The [compoundjs](http://compoundjs.com) library is an organization on [github](https://github.com/compoundjs).

Could not put stats like other repositories. But put links to documentation. What would be better to do?

**Comment by azat-co** [comment]
the right NPM name is `compound` https://www.npmjs.org/package/compound
the repo is under Anatoliy's name: https://github.com/1602/compound

so use that please! :smiley:

**Comment by azat-co** [comment]
probably it was changed at some point

**Comment by rands0n** [comment]
Ok, I packed :+1:

**Comment by azat-co** [comment]
:+1: great!!!
