### ISSUE TITLE
Link for hapi.js

### ISSUE THREAD

**Issue by sergeibershadsky** [azat-co/nodeframework#26]
Link for hapi.js leads to 404. The right github link is https://github.com/hapijs/hapi

**Comment by rands0n** [comment]
@sergeibershadsky Much better, make a PR for this operation :)

**Comment by rands0n** [comment]
I make the PR @sergeibershadsky :)

You can see this here #27

**Comment by sergeibershadsky** [comment]
thx :)

**Comment by azat-co** [comment]
:+1:
