### ISSUE TITLE
Whate MVC, Full-stack and Rest API difference?

### ISSUE THREAD

**Issue by thearabbit** [azat-co/nodeframework#40]
I am a new and interesting with node.js framework, but i don't know which the framework for me. becuase i don't understand for full-stack, rest api?
I come form PHP frameworke (Laravel).
Laravel components: MVC, RESTful Routing, Validation, CLI generator, View template, Authentication, Package development (composer/packagist), DB Query and ORM and more.
Can you explain me for the node.js framework like Laravel??????
Thanks...

**Comment by azat-co** [comment]
For a general overview you can read this article [PHP vs Node](http://webapplog.com/php-vs-node-js). Also take a look at Quora discussion: https://www.quora.com/Which-Node-js-framework-is-best-for-building-a-RESTful-API.

Also: http://stackoverflow.com/questions/9762453/node-js-frameworks/17514847.

**Comment by thearabbit** [comment]
Thanks
