### ISSUE TITLE
Sorting Lists?

### ISSUE THREAD

**Issue by MohammedFadin** [azat-co/nodeframework#43]
Hey!

I would like to contribute on this project since it helped me a lot! I was thinking to do an auto sorting the lists?

**Comment by rands0n** [comment]
Hey @MohammedFadin. Thank you for idea.

Fell free to send a pull request :)

**Comment by MohammedFadin** [comment]
Sure! I will.

**Comment by rands0n** [comment]
Niiiiice, I will wait for it :)
