### ISSUE TITLE
Submitting to https://github.com/sindresorhus/awesome-nodejs?

### ISSUE THREAD

**Issue by azat-co** [azat-co/nodeframework#58]
@randsonjs what do you think?

**Comment by rands0n** [comment]
Nice ideia @azat-co. This repo will be deleted? Or not?

**Comment by azat-co** [comment]
@randsonjs , no. why would we delete this repo? what I mean is to submit a link of this repo or the website to the awesome-nodejs registry

**Comment by rands0n** [comment]
Agree ;)
