### ISSUE TITLE
Is MEAN.js a full-stack framework?

### ISSUE THREAD

**Issue by chikh** [azat-co/nodeframework#62]
What the difference between MEAN.io and MEAN.js in terms of category? If there are no differences, then I suggest MEAN.js should be moved to the list of full-stack frameworks.

**Comment by azat-co** [comment]
yes, they are the same to me, mind sending a PR?

**Comment by chikh** [comment]
Sure https://github.com/azat-co/nodeframework/pull/63

**Comment by azat-co** [comment]
yes, they are the same to me, mind sending a PR?
