### ISSUE TITLE
website link is down

### ISSUE THREAD

**Issue by kaktus42** [azat-co/nodeframework#77]
`<p>See also <a href="http://nodewebmodules.com" target="_blank" rel="coworker" title="Node Web Modules">nodewebmodules.com</a></p>`

https://github.com/azat-co/nodeframework/blob/gh-pages/index.html#L1095

http://nodewebmodules.com is for sale.

**Comment by rands0n** [comment]
can you send a pull request?

**Comment by rands0n** [comment]
@azat-co remove the link?

**Comment by kaktus42** [comment]
if there is consent to remove the link, I can make a pull request. I wasn't sure if it should be changed

**Comment by rands0n** [comment]
yeah, the link not exist anymore. I think we can let only the name `nodewebmodules`.
